
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/snap/cmake/1560/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files/Tailscale/"
      - "/mnt/c/programming/vcpkg/"
      - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin/"
      - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/gerja/.dotnet/tools/"
      - "/snap/bin/"
    searched_directories:
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files/Tailscale/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/programming/vcpkg"
        - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin"
        - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/gerja/.dotnet/tools"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1560/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.18.33.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "find-v1"
    backtrace:
      - "/snap/cmake/1560/share/cmake-4.4/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files/Tailscale/"
      - "/mnt/c/programming/vcpkg/"
      - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin/"
      - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/gerja/.dotnet/tools/"
      - "/snap/bin/"
    searched_directories:
      - "/usr/local/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/usr/sbin/gmake"
      - "/usr/bin/gmake"
      - "/sbin/gmake"
      - "/bin/gmake"
      - "/usr/games/gmake"
      - "/usr/local/games/gmake"
      - "/usr/lib/wsl/lib/gmake"
      - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe/gmake"
      - "/mnt/c/WINDOWS/system32/gmake"
      - "/mnt/c/WINDOWS/gmake"
      - "/mnt/c/WINDOWS/System32/Wbem/gmake"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/gmake"
      - "/mnt/c/WINDOWS/System32/OpenSSH/gmake"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/gmake"
      - "/mnt/c/Program Files/dotnet/gmake"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/gmake"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/gmake"
      - "/mnt/c/Program Files/CMake/bin/gmake"
      - "/mnt/c/Program Files/Git/cmd/gmake"
      - "/mnt/c/Program Files/Tailscale/gmake"
      - "/mnt/c/programming/vcpkg/gmake"
      - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin/gmake"
      - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps/gmake"
      - "/mnt/c/Users/gerja/.dotnet/tools/gmake"
      - "/snap/bin/gmake"
      - "/usr/local/sbin/make"
      - "/usr/local/bin/make"
      - "/usr/sbin/make"
      - "/usr/bin/make"
      - "/sbin/make"
      - "/bin/make"
      - "/usr/games/make"
      - "/usr/local/games/make"
      - "/usr/lib/wsl/lib/make"
      - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe/make"
      - "/mnt/c/WINDOWS/system32/make"
      - "/mnt/c/WINDOWS/make"
      - "/mnt/c/WINDOWS/System32/Wbem/make"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/make"
      - "/mnt/c/WINDOWS/System32/OpenSSH/make"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/make"
      - "/mnt/c/Program Files/dotnet/make"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/make"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/make"
      - "/mnt/c/Program Files/CMake/bin/make"
      - "/mnt/c/Program Files/Git/cmd/make"
      - "/mnt/c/Program Files/Tailscale/make"
      - "/mnt/c/programming/vcpkg/make"
      - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin/make"
      - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps/make"
      - "/mnt/c/Users/gerja/.dotnet/tools/make"
      - "/snap/bin/make"
      - "/usr/local/sbin/smake"
      - "/usr/local/bin/smake"
      - "/usr/sbin/smake"
      - "/usr/bin/smake"
      - "/sbin/smake"
      - "/bin/smake"
      - "/usr/games/smake"
      - "/usr/local/games/smake"
      - "/usr/lib/wsl/lib/smake"
      - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe/smake"
      - "/mnt/c/WINDOWS/system32/smake"
      - "/mnt/c/WINDOWS/smake"
      - "/mnt/c/WINDOWS/System32/Wbem/smake"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/smake"
      - "/mnt/c/WINDOWS/System32/OpenSSH/smake"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/smake"
      - "/mnt/c/Program Files/dotnet/smake"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/smake"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/smake"
      - "/mnt/c/Program Files/CMake/bin/smake"
      - "/mnt/c/Program Files/Git/cmd/smake"
      - "/mnt/c/Program Files/Tailscale/smake"
      - "/mnt/c/programming/vcpkg/smake"
      - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin/smake"
      - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps/smake"
      - "/mnt/c/Users/gerja/.dotnet/tools/smake"
      - "/snap/bin/smake"
    found: false
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.7.11.0_x64__8wekyb3d8bbwe"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files/Tailscale/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/programming/vcpkg"
        - "/mnt/c/programming/RTSgame/build/vcpkg_installed/x64-windows/bin"
        - "/mnt/c/Users/gerja/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/gerja/.dotnet/tools"
        - "/snap/bin"
...
